### ISSUE TITLE
There is a Tappable Polygon ?

### ISSUE THREAD

**Issue by joandervieira** [OwnWeb/flutter_map_tappable_polyline#1]
There is a Tappable Polygon ?  PolygonLayerOptions

**Comment by tuarrep** [comment]
No. It's not planned.
Contributions are welcome.

**Comment by tomaszgruzla** [comment]
Can I tap a line between two points of this line?

**Comment by tuarrep** [comment]
It depends how they are spaced.

Tap is detected in a zone around each way points of the polyline. The
radius can be defined in options.

**Comment by tuarrep** [comment]
@tomaszgruzla Have a look to #4 we are talking about detecting taps between points

**Comment by HugoHeneault** [comment]
@tomaszgruzla A [PR](https://github.com/OwnWeb/flutter_map_tappable_polyline/pull/8) is allowing to tap between points of a line. Would you test it and come back to us?
