### ISSUE TITLE
Tappable polyline breaks onTap(latLng) in flutter_map

### ISSUE THREAD

**Issue by Mkohm** [OwnWeb/flutter_map_tappable_polyline#10]
The current implementation of tappable polyline breaks the onTap in flutter_map. I guess this is because everything is wrapped by the gesture detector. We should forward the tap event to the flutter_map onTap. But to do this we need to convert the tapped `TapUpDetails details` point into a `LatLng` any ideas on how to do this conversion?

**Comment by HugoHeneault** [comment]
Duplicate of #7
