### ISSUE TITLE
Multiple onTap called when polylines are close to each other

### ISSUE THREAD

**Issue by Mkohm** [OwnWeb/flutter_map_tappable_polyline#14]
If there are many polylines multiple onTap can be called. A solution where only the closest one will be triggered should be implemented. Will see what i can do about it later.

**Comment by tuarrep** [comment]
https://github.com/OwnWeb/flutter_map_tappable_polyline/blob/master/lib/flutter_map_tappable_polyline.dart#L185 Should prevent this

**Comment by Mkohm** [comment]
Unfortunately not - according to this: https://stackoverflow.com/questions/50336082/how-to-return-from-a-foreach-loop-in-dart and my observations, it will not return :) I am working on a fix as i am working with polylines that is close to each other.

**Comment by tuarrep** [comment]
Just replace foreach by a traditional for then.
