### ISSUE TITLE
There is a way to update position on the fly?

### ISSUE THREAD

**Issue by aweiand** [OwnWeb/flutter_map_tappable_polyline#22]
Hi!

I'm work on a map can change his layout over the time. In this case, I need a method to update the position of the polyline when a object "connected" to her change the position too. Is there a way to do this?

Thank's!

**Comment by tuarrep** [comment]
I don't understand your question well.

First, this package is just a wrapper around the original flutter_map Polyline.

All its positioning behavior is handled by this package.

But, the position of the polyline is calculated from the coordinates (ie real-world position) and the screen position of the map and its zoom.

So, the best way to move the polyline is to change the coordinates you've passed to its constructor.

Hope it helps.

**Comment by aweiand** [comment]
Hi @tuarrep !

Sorry, I don't explained it properly.... and testing again I have found the answer myself, thank`s!!
