### ISSUE TITLE
Conflict to actual flutter_map version

### ISSUE THREAD

**Issue by S-Man42** [OwnWeb/flutter_map_tappable_polyline#23]
Hi, when upgrading flutter_map to version 0.11.0 I get this error:

> Because flutter_map_tappable_polyline 1.2.0 depends on flutter_map ^0.10.1+1 and no versions of flutter_map_tappable_polyline match >1.2.0 <2.0.0, flutter_map_tappable_polyline ^1.2.0 requires flutter_map ^0.10.1+1.

Is there something I made wrong or do you need to add the compatibility?

**Comment by HugoHeneault** [comment]
We need to update the requirements. Until then you can use `dependency_overrides`. :)
