### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by fryette** [OwnWeb/flutter_map_tappable_polyline#26]
Would be nice to see it in null safety

**Comment by tuarrep** [comment]
Yes, this should be great. Perhaps you can try to draft a PR?

**Comment by fryette** [comment]
Sure, will do in next or after week if no news from others or author

**Comment by barbalex** [comment]
You will need to use latlong2 instead of latlong, as flutter_map itself does: https://github.com/fleaflet/flutter_map/blob/master/pubspec.yaml#L14

**Comment by barbalex** [comment]
flutter_map v0.13.1 has been released with null safety. So it looks like all needed dependencies exist.

**Comment by HugoHeneault** [comment]
Merged and 2.0.0 got published in 8d2b9293d41edd579d9f4f1a183c4f3a40310b9a
