### ISSUE TITLE
License

### ISSUE THREAD

**Issue by FaFre** [OwnWeb/flutter_map_tappable_polyline#29]
Please consider using another license for this project, as it will restrict users to publish apps based on that to the Apple AppStore.
See: https://www.fsf.org/news/2010-05-app-store-compliance

**Comment by tuarrep** [comment]
Thanks for pointing this out. It's embarrassing.

We'll have a look.
@HugoHeneault what is the position of OwnWeb on that?

**Comment by HugoHeneault** [comment]
Thanks for pointing this out. MIT should be better ;-)

**Comment by HugoHeneault** [comment]
For your information, we published an app using this pub without any issue... No surprise with the update though.

**Comment by FaFre** [comment]
Great! Yeah, it shouldn't be a problem if your the copyright holder yourself. However, I'm also not an expert and just read about it on stackoverflow :)
