### ISSUE TITLE
Problem with click

### ISSUE THREAD

**Issue by alexmo3** [OwnWeb/flutter_map_tappable_polyline#34]
Hi,

First of all I apologize if I'm asking nonsense (I'm new here) but, when I try to click on the map, the following error occurs. The double-click works very well.

════════ Exception caught by gesture ═══════════════════════════════════════════
Closure call with mismatched arguments: function 'MapPageState.build.<anonymous closure>'
Receiver: Closure: (dynamic) => Null
Tried calling: MapPageState.build.<anonymous closure>()
Found: MapPageState.build.<anonymous closure>(dynamic) => Null
════════════════════════════════════════════════════════════════════════════════
I/chatty  (16066): uid=10159(com.mysongs.mysongs_maps) 1.ui identical 23 lines
I/flutter (16066): alex: LatLng(latitude:-7.117835, longitude:-34.824728)
I/flutter (16066): alex: LatLng(latitude:-7.117835, longitude:-34.824728)

Flutter version

Flutter 2.5.0-5.2.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 19c61fed0d (8 days ago) • 2021-08-18 17:10:31 -0700
Engine • revision 7a4c4505f6
Tools • Dart 2.14.0 (build 2.14.0-377.7.beta)

**Comment by HugoHeneault** [comment]
Hi @alexmo3!

Welcome here. Would you please share your code so I can look on why you're having this issue?
Thanks a lot.

**Comment by HugoHeneault** [comment]
Hello @alexmo3 

Would you please provide us some repro code so we can work out this issue?

Thanks!

**Comment by manhlh** [comment]
Problem had fixed in last version 3.0.0.

**Comment by HugoHeneault** [comment]
Awesome! Thanks :-)
