### ISSUE TITLE
upgrade flutter_map to v0.14.0

### ISSUE THREAD

**Issue by barbalex** [OwnWeb/flutter_map_tappable_polyline#36]
After updating flutter_map to v0.14.0 I got:
```
Because flutter_map_tappable_polyline 3.0.0 depends on flutter_map ^0.13.1 and no versions of flutter_map_tappable_polyline match >3.0.0 <4.0.0, flutter_map_tappable_polyline ^3.0.0 requires flutter_map ^0.13.1.
So, because capturing depends on both flutter_map ^0.14.0 and flutter_map_tappable_polyline ^3.0.0, version solving failed.
pub get failed (1; So, because capturing depends on both flutter_map ^0.14.0 and flutter_map_tappable_polyline ^3.0.0, version solving failed.)
exit code 1
```

**Comment by barbalex** [comment]
I just saw that flutter_map contains a breaking change: "Added TapPosition to TapCallback". So now the first variable is TapPosition. Which means that https://github.com/OwnWeb/flutter_map_tappable_polyline/blob/master/lib/flutter_map_tappable_polyline.dart#L246 has to be changed.

**Comment by HugoHeneault** [comment]
Thanks for reporting!

I will work on it in upcoming days - busy week after coming back from holidays. If you have some time to prepare a PR, I'll review it.

**Comment by HugoHeneault** [comment]
Hello there!

I have updated `flutter_map` dep to 0.14.0 and made the according updates to the `onTap` event we forward. 

Thanks for reporting!

**Comment by HugoHeneault** [comment]
You can try overriding `latlong2` version. See https://dart.dev/tools/pub/dependencies#dependency-overrides

And ask the `flutter_map_dragmarker` to update its `latlong2` dep to `^0.8.1` 


```yaml
dependency_overrides:
   latlong2: 0.8.1
```

**Comment by barbalex** [comment]
@HugoHeneault 
Thanks a lot. I realize this was not an issue of flutter_map_tappable_polyline. But thanks for the working tip! And thanks for providing us this great tool.

**Comment by HugoHeneault** [comment]
Thanks for your words. No worries, we're here to help :-)

Happy cindig!
