### ISSUE TITLE
Points on Tap?

### ISSUE THREAD

**Issue by deezaster** [OwnWeb/flutter_map_tappable_polyline#39]
I need the points (coordinates), not only the position or the tag. Is this possible?

By the way, a very cool package!

**Comment by tuarrep** [comment]
I'm not sure to understand your needs.


Si you want to get the exact tap position on screen ?

**Comment by deezaster** [comment]
No, the tap position on screen i get it from the callback: 

`onTap: (polylines, tapPosition)`

What i need are the points of the map: **latitude** and **langitude**.

**Comment by tuarrep** [comment]
Understood.

It's not possible currently but adding this don't seems to be too hard.

I'll try to hack something when I find some spare time if no one dit it before.

**Comment by HugoHeneault** [comment]
@deezaster I have a PR on flutter_map which has some issues but works until you rotate the map (it then become less accurate, I'm still trying to figure it why)...

https://github.com/fleaflet/flutter_map/pull/1115

You can use our branch until it got merged, or even better, fork it on your own repo so you don't rely on something we could change later.

**Comment by tuarrep** [comment]
@HugoHeneault As thé polyline detection is made, we should be able to find winch offset of the polyline is the nearest from the tap.

It's not as accurate as your PR but it's doable.

If OP needs the exact tap position in term of lat/long it's not an issue for this repo

**Comment by deezaster** [comment]
Why i can not use the fork from my git repo?

`Because flutter_map_tappable_polyline >=3.1.0 depends on flutter_map from hosted and my_project depends on flutter_map from git, flutter_map_tappable_polyline >=3.1.0 is forbidden.`

**Comment by HugoHeneault** [comment]
@deezaster If it's fine on your side, you can close this issue. If you need more help, we're here. 

Thanks!
