### ISSUE TITLE
Example app : this app is using a deprecated version of the Android embedding.

### ISSUE THREAD

**Issue by HugoHeneault** [OwnWeb/flutter_map_tappable_polyline#43]
When building the example app we have this error message : 

```
This app is using a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to migrate this app to the V2 embedding.
Take a look at the docs for migrating an app: https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects
```

Shouldn't be long to fix :)

**Comment by k5924** [comment]
@HugoHeneault could I take this?

**Comment by k5924** [comment]
Sorry, forgot to mention that I submitted a PR for this issue in [#46](https://github.com/OwnWeb/flutter_map_tappable_polyline/pull/46)

**Comment by k5924** [comment]
@HugoHeneault realised I still have a PR open for this issue. Could you review it as its been open for about 6 months
