### ISSUE TITLE
Are there plans to upgrade the dependency on flutter_map to 3.0?

### ISSUE THREAD

**Issue by MaxiStefan** [OwnWeb/flutter_map_tappable_polyline#50]
Hi,

I tried to update the plugin locally to depend on flutter_map 3.0.0 and it seemed to work. However, when there are polygons on the map, the gesture callback on polylines seems to be omitted somehow.... No clue where this fails and I was curious if someone more knowledgeable has looking into it and would help migrating the plugin to 3.0.0

**Comment by HugoHeneault** [comment]
Hello there, 

We're quite busy here, I don't know if @tuarrep has more time than me. 

#49 could do the job (I haven't tested it), do try it and report any issues and we'll try to follow up :)

Thanks

**Comment by tuarrep** [comment]
I'll have a look this week

**Comment by HugoHeneault** [comment]
> I'll have a look this week

Awesome! 🙌

**Comment by S-Man42** [comment]
please upgrade the plugin!

**Comment by HugoHeneault** [comment]
I don't have time to do review this week, sorry :(

In the meantime you can use this branch in your pubspec.

**Comment by jean-gblr** [comment]
@HugoHeneault Hello do you have time this week then ? :D

**Comment by sirkalmi** [comment]
Hello, I did it, I'll push it when I get permission.

**Comment by sirkalmi** [comment]
Available here:
https://github.com/sirkalmi/flutter_map_tappable_polyline

**Comment by jtthrillson** [comment]
The new version of flutter_map (3.1.0) has a breaking change to PolylinePainter. I made quick commit to address that. 
https://github.com/jtthrillson/flutter_map_tappable_polyline

**Comment by Mike-3** [comment]
Any progress ?

**Comment by S-Man42** [comment]
There are many PRs to help you upgrading the plugin. Please take care of them an upgrade the package!

**Comment by Mike-3** [comment]
When do you think the new version will be operational?

**Comment by HugoHeneault** [comment]
I've merged #51 and will release a new version really soon.

**Comment by HugoHeneault** [comment]
Version 4.0.0 released :)
