### ISSUE TITLE
Update to flutter_map v4

### ISSUE THREAD

**Issue by HugoHeneault** [OwnWeb/flutter_map_tappable_polyline#52]
https://pub.dev/packages/flutter_map/versions/4.0.0-dev.1/changelog incoming. 

Any help appreciated as we don't have much time to do migration these days. 

Will try to get some time but can't do any promise, given the time needed to merge #51 😬

**Comment by JaffaKetchup** [comment]
*v5 😉

**Comment by JaffaKetchup** [comment]
Upgraded to FM v5 in #54.
