### ISSUE TITLE
FM v6 is coming soon

### ISSUE THREAD

**Issue by JaffaKetchup** [OwnWeb/flutter_map_tappable_polyline#58]
The next version of flutter_map is coming soon, with breaking changes for all users and plugins!

Expected CHANGELOG: https://github.com/fleaflet/flutter_map/blob/release-prep/CHANGELOG.md
Likely to be merged PR with significant impacts: fleaflet/flutter_map#1615
Release prep PR: fleaflet/flutter_map#1632
New documentation (path liable to change): https://docs.fleaflet.dev/v/v6-1
Expected migration instructions, suitable for most users: https://docs.fleaflet.dev/v/v6-1/getting-started/migrating-to-v6
List of commits since v5 (more to come): https://github.com/fleaflet/flutter_map/compare/v5.0.0...master

**Comment by Mike-3** [comment]
V6 is released

**Comment by HugoHeneault** [comment]
Hey @JaffaKetchup :)

Thanks for asking, really appreciate it :)
I'll do my best to merge it this week.

Quite busy here, still want to maintain the plugin but if things accumulate too much it might be better to merge everything in the main FM repo. 
I'd say it's also an FM team decision : do you want the codebase to grow and have have hands on more responsibility but also keep everything synced (better dx for FM users) or let each maintainer/team handle plugins update?

**Comment by HugoHeneault** [comment]
Great! @JaffaKetchup I'm finishing v6 migration, and it seems that `TapPosition` isn't exported anymore. 

I still need it, do I have to craft a PR on FM repo?

**Comment by JaffaKetchup** [comment]
Hmm, I'll need to track that down and open a PR - I guess I forgot to export it after getting rid of the Plugin API import. I'll have some time in about an hour so I can do it then, or feel free to do it now.

**Comment by JaffaKetchup** [comment]
Actually @HugoHeneault, something may have just changed, so I'll hold on for a minute. 

Do you think you could join the FM Discord and let me know your username?

**Comment by HugoHeneault** [comment]
I've joined the server and asked you as a friend
